version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:node12.13.0-chrome80-ff74
        environment:
          TERM: xterm
    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages

      - run:
          name: Environment
          command: |
            node --version
            npm --version
            yarn --version

      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Saving package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Linting
          command: yarn lint

      - run:
          name: Building the module
          command: yarn build

      - run:
          name: Preview Service Worker build
          command: cat lib/esm/mockServiceWorker.js

      - run:
          name: Running unit tests
          command: yarn test:unit

      - run:
          name: Running integration tests
          command: yarn test:integration
