version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:node12.0.0-chrome75
        environment:
          TERM: xterm
    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages

      - run:
          name: Environment
          command: |
            node --version
            npm --version
            yarn --version

      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Saving package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Building the module
          command: yarn build

      - run:
          name: Distributed Service Worker preview
          command: cat lib/mockServiceWorker.js

      - run:
          name: Unit tests
          command: yarn test:unit

      - run:
          name: Integration tests
          command: yarn test:integration
